### ISSUE TITLE
Obtain Strava Token Without a browser

### ISSUE THREAD

**Issue by OvidiuTa** [liskin/strava-offline#15]
Hello,

thanks for providing such a tool. I am trying to use this tool and initiate the first session, but unfortunately I am running it in a machine (Cloud) to which I cannot get a GUI for the browser.
Is there any way to do the first authorization in an other way?

Many thanks!

**Comment by OvidiuTa** [comment]
Thanks for the hint! I was trying to run, then I got some errors regarding pulling bikes data. After going into the code and commented everything related to bikes, it work.. not sure what is the casuse.

_Traceback (most recent call last):
  File "/home/azureuser/.local/bin/strava-offline", line 8, in <module>
    sys.exit(cli())
  File "/home/azureuser/.local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/azureuser/.local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/azureuser/.local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/azureuser/.local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/azureuser/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/azureuser/.local/lib/python3.8/site-packages/strava_offline/config.py", line 36, in wrapper
    return f(config_class(**config_kwargs), **f_kwargs)
  File "/home/azureuser/.local/lib/python3.8/site-packages/strava_offline/cli.py", line 29, in cli_sqlite
    sync.sync(config=config, strava=strava)
  File "/home/azureuser/.local/lib/python3.8/site-packages/strava_offline/sync.py", line 92, in sync
    sync_bikes(strava, db)
  File "/home/azureuser/.local/lib/python3.8/site-packages/strava_offline/sync.py", line 78, in sync_bikes
    table_bike.upsert(db, strava.get_bikes())
  File "/home/azureuser/.local/lib/python3.8/site-packages/strava_offline/strava.py", line 72, in get_bikes
    return self.get_athlete()['bikes']
KeyError: 'bikes'_
