### ISSUE TITLE
Missing access token parameter

### ISSUE THREAD

**Issue by l1gi** [liskin/strava-offline#17]
Hello,

I have setup strava-offline a week ago, everything worked including gpx download. Now I came back to it and run `strava-offline sqlite` with following result:

```
Traceback (most recent call last):
  File "/home/ligi/.local/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 528, in request
    url, headers, data = self._client.add_token(
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 217, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ligi/.local/bin/strava-offline", line 8, in <module>
    sys.exit(cli())
  File "/home/ligi/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ligi/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ligi/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ligi/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ligi/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ligi/.local/lib/python3.10/site-packages/strava_offline/config.py", line 36, in wrapper
    return f(config_class(**config_kwargs), **f_kwargs)
  File "/home/ligi/.local/lib/python3.10/site-packages/strava_offline/cli.py", line 29, in cli_sqlite
    sync.sync(config=config, strava=strava)
  File "/home/ligi/.local/lib/python3.10/site-packages/strava_offline/sync.py", line 92, in sync
    sync_bikes(strava, db)
  File "/home/ligi/.local/lib/python3.10/site-packages/strava_offline/sync.py", line 78, in sync_bikes
    table_bike.upsert(db, strava.get_bikes())
  File "/home/ligi/.local/lib/python3.10/site-packages/strava_offline/strava.py", line 72, in get_bikes
    return self.get_athlete()['bikes']
  File "/home/ligi/.local/lib/python3.10/site-packages/strava_offline/strava.py", line 67, in get_athlete
    r = self._session.get("https://www.strava.com/api/v3/athlete")
  File "/home/ligi/.local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/ligi/.local/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 547, in request
    token = self.refresh_token(
  File "/home/ligi/.local/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 496, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 448, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 451, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
```
I also see that there is this in the README:
`(That settings page also lists Your Access Token but this won't let you download private activities or see names of bikes. Therefore its use is not supported in strava-offline.)
`

Any advice, please?

Thank you,
m.

**Comment by liskin** [comment]
This looks like the `refresh_token` is no longer valid, so you'll need to relogin.
There isn't currently a subcommand to do that, but you can manually `rm ~/.config/strava_offline/token.json`.

Not sure why the token became invalid, though. Perhaps you changed your password, or revoked strava_offline's authorization in Strava's settings?

**Comment by l1gi** [comment]
Okay, removed the token.json and it is working again. I don't remember any event which could cause this. Thank you!
m.
